name = "50501 Santa Cruz"
description = "Santa Cruz Chapter of the 50501 Movement"
keywords = "50501, Santa Cruz, protest"
image = "SantaCruzLogo.png"
theme = "dark"
primary_color = "#1e49c6"
text_align = "center"
base_url = "https://50501santacruz.github.io/"

[[sections]]
title = "‼ ALERT: CALIFORNIA IS UNDER ATTACK ‼"
item_style = "outline"
direction = "row"
icon_size = "500px"
[[sections.items]]
title = "50501 Santa Cruz calls for weekly peaceful protest until ICE/National Guard/USMC leave the city of Los Angeles. Protest peacefully with American and California flags along sidewalks in locations that are safe and convenient for you. Stay out of traffic. Do not remain in areas where violence or looting are occurring. Carry appropriate PPE. RESIST!"
url = "#"

[[sections]]
title = "Next Event"
item_style = "outline"
direction = "row"
icon_size = "500px"
[[sections.items]]
icon = "https://github.com/50501SantaCruz/50501SantaCruz.github.io/blob/32223a418d02b4f8cd29526ec8e55193f8372abc/dist/img/NO%20KINGS_resized.png?raw=true"
url = "https://www.mobilize.us/mobilize/event/791792/"

[[sections]]
title = "Volunteer With Us"
description = "Help Us Organize Epic Protests!"
direction = "column"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
title = "Volunteer Sign-up"
url = "https://cryptpad.fr/form/#/2/form/view/-0Ft6rtDhFbyFOmseFi0w+R9uFzjXmGgDkaBopd8rAo/"

[[sections]]
title = "Contact Us"
direction = "column"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
title = "Email"
url = "mailto:santacruz@50501.ca"

[[sections]]
title = "Links"
description = "Follow us on Social Media"
direction = "column"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/bluesky/ffffff"
title = "Bluesky"
url = "https://bsky.app/profile/50501santacruz.bsky.social"
[[sections.items]]
icon = "https://cdn.simpleicons.org/x/ffffff"
title = "X.com"
url = "https://x.com/50501SantaCruz"
[[sections.items]]
icon = "https://cdn.simpleicons.org/lemmy/ffffff"
title = "Lemmy"
url = "https://50501.chat/u/santacruz"

[[sections]]
title = "50501 California"
description = "Learn more about the 50501 movement in California"
item_style = "outline"
icon_size = "45px"
[[sections.items]]
icon = "https://50501ca.org/static/media/california.a946446044a9ee9faec3.png"
title = "Visit 50501ca.org"
url = "https://50501ca.org/"

[[sections]]
title = "Our Friends and Partners"
description = "Check out these other local activism groups"
direction = "row"
item_style = "outline"
icon_size = "100px"
[[sections.items]]
icon = "https://images.squarespace-cdn.com/content/v1/65e24eb0339d3355610d8848/ff5726a8-4e00-4013-8fc7-94f6ead06c9b/ISCC+Logo_Transparent_large.png?format=1500w"
title = "Indivisible Santa Cruz County"
url = "https://www.indivisiblesantacruzcounty.com/"
